# Generated by Django 5.2.8 on 2025-12-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=50)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('temperamento', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('imagen', models.URLField()),
            ],
        ),
    ]
